#+begin_src text
               ____           _      _
              (|   \         | | o  | |
               |    | __ _|_ | |    | |  _   ,
              _|    |/  \_|  |/  |  |/  |/  / \_
             (/\___/ \__/ |_/|__/|_/|__/|__/ \/
                             |\
                             |/
#+end_src


Welcome! These are the dotfiles that I use in my daily-driver Void system. The goal was to build a comfy, minimalist system that doesn't take me out of my workflow. Ever. For that reason I'm using Emacs Keybinds pretty much everywhere. If you don't need/want that, just don't install ~xkeysnail~.

------

*** System Information
- *Distribution*: Void Linux
- *Window Manager*: bspwm
- *Shell*: Bash
- *Terminal*: Urxvt
- *Widgets*: [[https://github.com/elkowar/eww][Eww]], [[https://github.com/brndnmtthws/conky][Conky]]
- *Application Launcher*: [[Rofi][Rofi]]
- *Music Player*: Spicetify
- *Notification Daemon*: End

--------

*** Screenshots
Coming soon

** Getting Started
*** Packages
On my Void system I use the following packages. Just install their dependencies/build tools as well.
**** From XBPS
~picom~, ~firefox~, ~emacs-gtk3~, ~conky~, ~zathura~, ~rofi~, ~sxhkd~, ~bspwm~, ~i3lock-color~
**** From XBPS-SRC
~spotify~, ~discord~
**** From Source
~eww~, ~xkeysnail~, ~spicetify~

*** Firefox Extensions
I'm using my own [[https://github.com/lucalabs-de/key-jump-browser-extension][fork]] of Kenneth Sundqvist's [[https://github.com/KennethSundqvist/key-jump-browser-extension][Key Jump]] extension to allow for keyboard-only navigation in Firefox.

*** Additional Configuration
**** Using template config files
I wanted to be as flexible as possible when it comes to color schemes and dark/light themes, so I'm managing all colors via Xresources. Unfortunately, many programs use their own configuration files for color customization and don't care about Xresources. To get around that limitation, I'm using template versions of these config files which contain placeholders for Xresources colors. I then run a [[.scripts/setup-configs][script]] to fill those placeholders using the corresponding Xresources colors. Files starting with three ___underscores are templates.
**** Disable password prompts when running sudo
Some commands, like ~xkeysnail~ and ~poweroff~ have to be run with ~sudo~, which is a problem if we want to use them in scripts. To avoid being prompted for a password when running these commands, we can add the following line to the ~sudoers~ file, using ~sudo visudo~:

#+begin_src
<USER> ALL=NOPASSWD: <PATH TO COMMAND>
#+end_src

Alternatively, we can create a new file in ~/etc/sudoers.d~ and manage the commands there. To add the most common commands, you can use the following command

#+begin_src bash
  cat <<EOT >> /etc/sudoers.d/nopasswds
  $USER $HOSTNAME = (root) NOPASSWD: /sbin/shutdown
  $USER $HOSTNAME = (root) NOPASSWD: /sbin/reboot
  $USER $HOSTNAME = (root) NOPASSWD: /sbin/wpa_supplicant
  $USER $HOSTNAME = (root) NOPASSWD: /sbin/poweroff
  $USER $HOSTNAME = (root) NOPASSWD: /bin/xkeysnail
  $USER $HOSTNAME = (root) NOPASSWD: /bin/light
  EOT
#+end_src
