#+begin_center
________          __    _____.__.__                 
\______ \   _____/  |__/ ____\__|  |   ____   ______
 |    |  \ /  _ \   __\   __\|  |  | _/ __ \ /  ___/
 |    `   (  <_> )  |  |  |  |  |  |_\  ___/ \___ \ 
/_______  /\____/|__|  |__|  |__|____/\___  >____  >
        \/                                \/     \/
#+end_center

Welcome! These are the dotfiles that I use in my daily-driver Void system. The goal was to build a comfy, minimalist system that doesn't take me out of my workflow. Ever. For that reason I'm using Emacs Keybinds pretty much everywhere. If you don't need/want that, just don't install ~xkeysnail~.

------

*** System Information
- *Distribution*: Void Linux
- *Window Manager*: BSPWM
- *Shell*: Bash
- *Terminal*: Urxvt
- *Widgets*: [[https://github.com/elkowar/eww][Eww]]
- *Application Launcher*: [[Rofi][Rofi]]
- *Music Player*: Spicetify

--------
 
*** Screenshots
Coming soon

** Getting Started
*** Packages
On my Void system I use the following packages. Just install their dependencies/build tools as well.
**** From XBPS
~picom~, ~firefox~, ~emacs-gtk3~, ~conky~, ~zathura~, ~rofi~, ~sxhkd~, ~bspwm~
**** From XBPS-SRC
~spotify~, ~discord~
**** From Source
~eww~, ~xkeysnail~, ~spicetify~

*** Firefox Extensions
I'm using Kenneth Sundqvist's [[https://github.com/KennethSundqvist/key-jump-browser-extension][Key Jump]] extension to allow for keyboard-only navigation in Firefox.

*** Additional Configuration
**** Disable password prompts when running sudo
Some commands, like ~xkeysnail~ and ~poweroff~ have to be run with ~sudo~, which is a problem if we want to use them in scripts. To avoid being prompted for a password when running these commands, we can add the following line to the ~sudoers~ file, using ~sudo visudo~:

#+begin_src 
<USER> ALL=NOPASSWD: <PATH TO COMMAND>
#+end_src

Alternatively, we can create a new file in ~/etc/sudoers.d~ and manage the commands there. To add the most common commands, you can use the following command

#+begin_src bash
cat <<EOT >> /etc/sudoers.d/nopasswds
$USER $HOSTNAME = (root) NOPASSWD: /sbin/shutdown
$USER $HOSTNAME = (root) NOPASSWD: /sbin/reboot
$USER $HOSTNAME = (root) NOPASSWD: /sbin/wpa_supplicant
$USER $HOSTNAME = (root) NOPASSWD: /sbin/poweroff
$USER $HOSTNAME = (root) NOPASSWD: /bin/xkeysnail
EOT
#+end_src

