#!/bin/sh
# Stolen from https://github.com/depsterr/mfetch
# Adapted by lucalabs-de

# read system info
read -r host < /proc/sys/kernel/hostname
read -r kernel < /proc/sys/kernel/osrelease
. /etc/os-release

# Get wm from xinitrc
while read -r line; do
    [ "${line#exec }" = "$line" ] || wm="${line#exec }"
done < "$HOME/.xinitrc"

# Colors and palette method stolen from dylanaraps pftech
# https://github.com/dylanaraps/pfetch
c0='[0m';
c1='[31m'; c2='[32m'
c3='[33m'; c4='[34m'
c5='[35m'; c6='[36m'
c7='[37m'; c8='[38m'
palette="[7m$c1 $c1 $c2 $c2 $c3 $c3 $c4 $c4 $c5 $c5 $c6 $c6 [m"

# Output
printf '%s\n' "
    ${c2}      /\\
    ${c2}     /\\*\\       ${USER}${c0}@${c2}${host}
    ${c2}    /\\O\\*\\      ${c6}os${c0}      ${PRETTY_NAME}
    ${c2}   /*/\\/\\/\\     ${ARTR3}${c6}kernel${c0}  ${kernel}
    ${c2}  /\\O\\/\\*\\/\\    ${c6}shell${c0}   ${SHELL##*/}
    ${c2} /\\*\\/\\*\\/\\/\\   ${c6}wm${c0}      ${wm}
    ${c2} |O\\/\\/*/\\/O|   
    ${c3}      ||        
    ${c3}      ||        ${palette}
        "
