#!/bin/bash

THEME="$HOME/.themes/night/colors"
WALLPAPER="$HOME/.themes/chwallpaper-night.png"

feh --bg-fill $WALLPAPER

/bin/notify-send --hint=string:x-dunst-stack-tag:battery -u low "Night Mode" "It's getting late..."

# As of now, this only changes the wallpaper. To update the colors, I need to find a way to reload all the windows.
