#!/bin/bash

TIME_IN_SECS=$(( $(date +%s) - $(date -d '00:00:00' +%s) ))
NIGHT_TIME=$(cat $HOME/.themes/NIGHT_THEME_TIME)
DAY_TIME=$(cat $HOME/.themes/DAY_THEME_TIME)

if [[ $TIME_IN_SECS -gt $NIGHT_TIME ]] || [[ $TIME_IN_SECS -lt $DAY_TIME ]]
then
    THEME="$HOME/.themes/night/colors"
    WALLPAPER="$HOME/.themes/wallpaper-night.png"
    /bin/notify-send --hint=string:x-dunst-stack-tag:battery -u low "Night Mode" "It's getting late..."
else
    THEME="$HOME/.themes/day/colors"
    WALLPAPER="$HOME/.themes/wallpaper-day.png"
fi

cp $WALLPAPER "$HOME/.themes/wallpaper.png"

feh --bg-fill $WALLPAPER
