#!/bin/bash

# This script is mainly written for a second screen that's connected to a laptop, YMMV

# the screen we want to connect to (check xrandr for this information)
NEW_SCREEN="HDMI-1"
RESOLUTION="3440x1440"

OLD_SCREEN="eDP-1"
ADAPTIVE_RESOLUTION="2560x1440"

if ! [ "$(xrandr -q | grep "^$NEW_SCREEN connected")" ]; then
    echo "$NEW_SCREEN not connected"
    exit 1
fi

# connect screen
xrandr --dpi 97 --output "$OLD_SCREEN" --mode "$ADAPTIVE_RESOLUTION"
xrandr --dpi 97 --output "$NEW_SCREEN" --right-of "$OLD_SCREEN" --mode "$RESOLUTION"

sleep 1

# fix wallpaper
feh --bg-fill "$HOME/.themes/wallpaper.jpg"

# fix bspwm desktops
bspc monitor "$OLD_SCREEN" -d 1 2 3 4 5
bspc monitor "$NEW_SCREEN" -d 6 7 8 9 10

# open eww widgets on new screen
eww open indicator-widescreen # you probably need to tweak this widget if your second monitor is not 3440x1440 (2560x1440 might be fine)

echo "Connected to $NEW_SCREEN"
