#!/bin/bash

# quick script to fill all template configs
regex="___(.+)"

find $HOME/.config $HOME/.mozilla -name '___*' | while read -r file; do
    [[ $file =~ $regex ]]

    output=${BASH_REMATCH[1]}

    . $HOME/.scripts/fill-template "$file" "$(dirname $file)/$output"
done
